# permissions for end users to view fios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fio-viewer-role
rules:
- apiGroups:
  - perf.rhocplab.com
  resources:
  - fios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - perf.rhocplab.com
  resources:
  - fios/status
  verbs:
  - get
