# permissions for end users to view perfutils.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: perfutils-viewer-role
rules:
- apiGroups:
  - perf.rhocplab.com
  resources:
  - perfutils
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - perf.rhocplab.com
  resources:
  - perfutils/status
  verbs:
  - get
