# permissions for end users to edit perfutils.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: perfutils-editor-role
rules:
- apiGroups:
  - perf.rhocplab.com
  resources:
  - perfutils
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perf.rhocplab.com
  resources:
  - perfutils/status
  verbs:
  - get
