apiVersion: perf.rhocplab.com/v1
kind: Fio
metadata:
  name: fio-sample
spec:
  nodeName: master-2
  fio_args:
    - --name=fsyncwrite
    - --ioengine=sync
    - --fdatasync=1
    - --iodepth=1
    - --rw=write
    - --bs=4m 
    - --size=256m
